name: sorting-network
version: 0.1.0.0
github: Javran/sorting-network
license: Apache-2.0
author: Javran Cheng
maintainer: javran.c@gmail.com
description: Sort small lists with sorting network.

ghc-options:
  - -Wall

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoUnicodeSyntax
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - template-haskell
    - vector

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - sorting-network
      - QuickCheck
      - hspec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
